---
title: "Introducción al procesamiento de datos con R para Ciencias Sociales"
authot: 
  - name: Pablo Tiscornia
site: distill::distill_website
---

## Presentación
  
El taller tiene como principal objetivo introducir a los y las participantes en el mundo de R y la programación para producir información estadística descriptiva. La idea es centrarse en cómo encarar un proyecto que involucre meter manos en los datos, desde cómo nombrar las carpetas o archivos, importarlos para acceder a la información, limpiar  y procesarla hasta como visualizar, analizar y comunicar los hallazgos.

## ¿Para quién?

Para toda aquella persona que quiera / necesite trabajar con datos de una forma más sistemática, ordenada y productiva. No se requiere conocimientos previos de algún lenguaje en particular, aunque siempre es de ayuda haberse cruzado al menos con una sintaxis o haber utilizado alguna fórmula en Excel.

Lo de _Ciencias Sociales_ es una excusa! Los ejemplos serán a partir de bases con las que suelo estar cómodo, pero el contenido es válido para cualquier campo/disciplina/profesión.

## ¿Cómo?

Las clases del taller serán teórico-prácticas. Por cada presentación temática se plantearán ejercicios sobre lo visto, abordando al mismo tiempo las dudas que puedan surgir. Se priorizará la utilización del programa durante la clase. 

---

## Cronograma: 

__Duración del curso:__ 12hs.

__Cantidad de encuentros:__ 4.

__Cantidad de horas por encuentro:__ 3hs.

__Día y horario de cursada:__ Jueves, de 18 a 21hs.
  
__Fecha de inicio__: 18 de noviembre.

__Fecha de finalización__: 9 de diciembre

