---
title: "Tendencias de Google"
author: "Pablo Tiscornia"
output: 
  html_document:
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	#echo = FALSE,
	message = FALSE,
	warning = FALSE
)
options(scipen = 999)
Sys.setenv(TZ='America/Argentina/Buenos_Aires')
```

```{r}
#install.packages('gtrendsR')
# if (!require("devtools")) install.packages("devtools")
# devtools::install_github("PMassicotte/gtrendsR")

library(gtrendsR)
library(tidyverse)
library(gt)
```


## Analizando evolución del término _#ParoDocente_ en Argentina

```{r echo=FALSE}
tendencia <- gtrends(
  keyword = c("paro docente"), 
  gprop = "web",
  geo = "AR",
  time = "2018-01-01 2021-07-26",
  hl = "en")


tendencia_serie <- tendencia$interest_over_time

# Gráfico
tendencia_serie %>% 
  mutate(hits = as.numeric(case_when(hits == "<1" ~ "0",
                          TRUE ~ hits))) %>% 
  ggplot(aes(x = as.Date(date), y = hits, group = keyword, col = keyword)) +
  geom_line() +
  geom_smooth(span=0.2,se=FALSE) +
  theme_bw() + 
  labs(title = "Tendencia #Paro Docente", 
       x = "Fecha", y = "Interés relativo", fill = "Término")
```


## Tópicos relacionados

```{r}
tendencia_topicos <- tendencia$related_topics %>% 
  mutate(subject = as.numeric(ifelse(subject %in% c(0:100), subject, NA)))


tendencia_topicos %>% 
  filter(!is.na(subject)) %>% 
  ggplot(aes(x = fct_reorder(value, subject), y = subject)) + 
  geom_col() +
  coord_flip() +
  theme_bw() +
  labs(title = "Tópicos relacionados con la búsqueda de 'Paro de subtes'",
       x = "Tópico", y = "Alcance")
```


### Tendencia de los términos: _#ParoDocente_ + _#Paritaria_
```{r}
conflicto <- gtrends(
  keyword = c("Paro docente", "Paritaria docente"),
  gprop = "web",
  geo = "AR",
  time = "2018-01-01 2021-07-26", 
  hl = "es-AR")


conflicto_serie <- conflicto$interest_over_time

### Pasajes, Despegar, Booking, Vuelos
conflicto_serie %>% 
  mutate(hits = as.numeric(case_when(hits == "<1" ~ "0",
                          TRUE ~ hits))) %>% 
  ggplot(aes(x = date, y = hits, group = keyword, col = keyword)) +
  geom_line() +
  geom_smooth(span=0.2, se=FALSE) +
  theme_bw() + 
  labs(title = "Tendencia #Paro docente + #Paritaria docente", 
       x = "Fecha", y = "Interés relativo", fill = "Término") +
  scale_color_brewer(palette = 
                       #"Accent"
                       "Set1")
```



