---
title: "Introducción al procesamiento de datos con R para Ciencias Sociales"
authot: 
  - name: Pablo Tiscornia
site: distill::distill_website
---

## Objetivos del curso
  
El presente taller tiene como objetivo principal introducir a los y las participantes en el aprendizaje del lenguaje de programación “R”, centrandose en los aspectos de importación de datos, limpieza, tratamiento, visualización y análisis.

---

### Contenido:


## Módulo I: Presentación del lenguaje R.
  
  + R base.
  + Valores
  + Vectores (variables)
  + Funciones
  + Objetos
  + Data frames (bases de datos)
  + Paquetes
  + Importación de datos (formatos _.txt_, _.csv_, _.xlsx_, _.sav_, _.dat_)


## Módulo II: Procesamiento de datos con el paquete `Tidyverse`:

  + Limpieza de Base de datos: Renombrar y recodificar variables.
  + Seleccionar variables, ordenar y agrupar la base de datos
  + Creación de nuevas variables
  + Aplicar filtros sobre la base de datos (definir poblaciones)
  + Tratamiento de valores faltantes (missing values/ NA´s)
  + Construir medidas de resumen de la información
  + Tratamiento de variables numéricas
  + Tratamiento de variables de texto


## Módulo III: Visualización de la información
  
  + Gráficos elaborados en R (función “ggplot”): 
  + Gráficos de línea, barras, Boxplots y distribuciones de densidad
  + Parámetros de los gráficos: Leyendas, ejes, títulos, notas, colores, escala
  + Gráficos en masa (generación de múltiples gráficos en pocas líneas de código)


## Módulo IV: Introducción al web scraping
  
  + Aspectos básicos de html
  + Recopilación y procesamiento de datos de la web

<br>
  
### Cronograma: 

__Duración del curso:__ 12hs.

__Cantidad de clases:__ 6.

__Cantidad de horas por clase:__ 2hs.

__Día y horario de cursada:__ Martes de 9 a 11hs. am.
  
__Fecha de inicio__: 15 de Junio de 2021.

__Fecha de finalización__: 20 de julio de 2021.


<br><br>

